### ISSUE TITLE
How to pull hex values from the app?

### ISSUE THREAD

**Issue by Jacksonbm1** [newt10/homebridge-broadlink-rm-enhanced#24]
I have a broadlink rm pro4 and I have it connected to homebridge. However, I can't seem to set up my devices. Part of the problem is that my ac unit doesn't have the remote it came with, so I just pulled an example off of the broadlink app. Thus, the app works, but I don't know what frequency it's going off of. Is there a way for me to find out via homebridge or in the app? i've dug around, but can't figure out.

**Comment by newt10** [comment]
Unfortunately, rm pro4 will not work with this version of the plugin, I am working on updates and should have something available in a month.
