### ISSUE TITLE
does this plusin support tempStepSize?

### ISSUE THREAD

**Issue by hamwong** [newt10/homebridge-broadlink-rm-enhanced#27]
Hi, Thanks for this great plugin, please advise does this plugin support tempStepSize?
I can't found a way to change the temperature from 0.5 to 1, it is annoying.

**Comment by newt10** [comment]
Can you share pics?

**Comment by hamwong** [comment]
https://developers.homebridge.io/#/characteristic/CoolingThresholdTemperature
ios14 should have changed min step to 0.5, but it also allow user to change to 1.0, 2.0 or even more, so if I set the min step to 1, when I change temp from 20 to 22, temp value will change from 20>21>22 not 20 >20.5>21>21.5>22,
